language: go
go:
  - 1.3
  - tip
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_retry sudo apt-get install -qq libcap-dev; fi
notifications:
  irc:
    channels:
      - "chat.freenode.net##hl-t"
    skip_join: true
