language: go
go:
  - 1.5.2

os:
  - linux
#  - osx

addons:
  apt:
    packages:
      - gcc-multilib
      - libc6-dev:i386
      - libcap-dev
      - libcap-dev:i386

sudo: false

install:
  - go get -v -t ./...
script:
  - source ./.travis/script
after_success:
  - source ./.travis/after_success

env:
  # GITHUB_TOKEN for automatic releases
  - secure: "VMHoQgsc2dgENcBtjoTJyy69gV+V+uTByyjsgtfjd7XdBBPpTFZQOHkhGNlQcwsQhHf4QZIW+ediQTqpqnlw5qIK3Sax9RbFOoyw4Eb3f7CBU8xecwzM+JejdZXTCiYY6sV2NvTZJWnKyiqamO3AcPLwIW/fqNjE80I/Xr3KfMQ="
